theme = "catppuccin_macchiato"

[editor]
shell = ["nu", "-c"]
line-number = "relative"

[keys.normal]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"D" = ["extend_to_line_end", "delete_selection"]

[keys.select]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
